= Autograding in GitHub Classroom
:toc:
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]
:sectnums:
:experimental:  // for the keyboard macro

Here is my preamble paragraph, but I could really place the TOC anywhere! Lorem ipsum foo bar baz.

toc::[]

== adoc-Demo in README

CAUTION: This chapter is off-topic, but wanted to cover it.

=== Admonitions

[NOTE]
====
A sample note admonition.
We can use gemoji icons in the Asciidoctor markup.
We assign an icon name to the document
attributes `tip-caption`, `note-caption` and `important-caption`.
====

TIP: It works!

IMPORTANT: Asciidoctor is awesome, don't forget!

CAUTION: Don't forget to add the `...-caption` document attributes in the header of the document on GitHub.

WARNING: You have no reason not to use Asciidoctor.

=== Images (UML-Diagrams)

==== plantuml-diagram only w/o puml-file

[source,asciidoc]
----
 image::http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKhEIImkLWX8BIhEprEevb9Gq4tBB2ekyKlCJRLI22ufoinBnovOo-MGcfS2D080[]
----

will be rendered to

image::http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKhEIImkLWX8BIhEprEevb9Gq4tBB2ekyKlCJRLI22ufoinBnovOo-MGcfS2D080[]

You can easily reverse-engineer this diagram at

https://www.plantuml.com/plantuml/uml/

Just paste the url and click kbd:[Decode URL]

==== plantuml-diagram reffering to puml-file

.referring to <project-root>/plantuml/cld.puml
[source,asciidoc]
----
 image::http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/htl-leonding/autograding-demo-jdk/main/plantuml/cld.puml[]
----

image::http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/htl-leonding/autograding-demo-jdk/main/plantuml/cld.puml[]

* When you update your puml-file, this image will be updated too

IMPORTANT: Maybe in private repos permission issues will occur

=== Collapsible

.see content
[%collapsible]
====
* Hello world
====

=== Source Code

CAUTION: Unfortunately github doesn't support asciidoctor-includes

[source,asciidoc]
----
 [source, java]
 ----
 include::https://raw.githubusercontent.com/htl-leonding/autograding-demo-jdk/main/hello-world/src/main/java/at/htl/helloworld/Main.java[]
 ----
----


[source,java,linenos]
----
include::https://raw.githubusercontent.com/htl-leonding/autograding-demo-jdk/main/hello-world/src/main/java/at/htl/helloworld/Main.java[]
----


=== Sources

* https://blog.doubleslash.de/github-readme-r-i-p-markdown-es-lebe-asciidoc/[Github-README: R.I.P. Markdown – es lebe AsciiDoc!]
* https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74[GitHub Flavored Asciidoc (GFA)]
* https://gist.github.com/powerman/d56b2675dfed38deb298[Asciidoc cheatsheet for GitHub]
* https://www.informatik.htw-dresden.de/~zirkelba/praktika/se/arbeiten-mit-git-und-asciidoc/[Arbeiten mit Git und AsciiDoc] <- geniale Seite!
* https://blog.anoff.io/2018-07-31-diagrams-with-plantuml/[Markdown native diagrams with PlantUML]
* https://blog.anoff.io/puml-cheatsheet.pdf[plantuml-cheatsheet]
* https://github.com/github/markup#markups[supported markups in github]


== Autograding

=== Set Java-Version

* gh-autograding uses per default java 11 (🤯)
* but there is a workaround: https://github.com/education/autograding/issues/18#issuecomment-627432895[workaround for java version]

* Basically you get the default gh-actions for autograding and add the installation for java 18
+
..github/workflows/classroom.yml
[%collapsible]
====
[source,yaml]
----
    name: GitHub Classroom Workflow

    on:
      push:
      workflow_dispatch:

    permissions: write-all

    jobs:
      build:
        name: Autogradingx
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
              distribution: 'temurin'
              java-version: '17'
              cache: 'maven'
          - uses: education/autograding@v1
----
====
+
..github/classroom/autograding.json
[%collapsible]
====
[source,json]
----
{
  "tests": [
    {
      "name": "MainTest",
      "setup": "cd hello-world && ./mvnw compile",
      "run": "cd hello-world && ./mvnw test",
      "input": "",
      "output": "",
      "comparison": "included",
      "timeout": 10,
      "points": 5
    }
  ]
}
----
====

* Because gh-classroom overwrites the workflow in the template-repo, it is recommended to remove the autograding when editing the assignment in classroom.

* Copy the .github-folder into the template-repo and it will work

TIP: Noticed, that sometimes you have to run the workflow twice after editing the classroom.yml.

=== Autograding failure: HttpError: Resource not accessible by integration

* add the `permissions: write-all` to classroom.yml


=== Sources

* https://www.youtube.com/playlist?list=PL9rLYHglJZYVFKGRvnvnYdsLxHqnZ-jPX[mirah - github teacher basics^] <- recommend this tutorial







