= Autograding in GitHub Classroom
:toc:
:toc-placement!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:sectnums:
:experimental:  // for the keyboard macro

Here is my preamble paragraph, but I could really place the TOC anywhere! Lorem ipsum foo bar baz.

toc::[]

== adoc-Demo in README

=== Admonitions

[NOTE]
====
A sample note admonition.
We can use gemoji icons in the Asciidoctor markup.
We assign an icon name to the document
attributes `tip-caption`, `note-caption` and `important-caption`.
====

TIP: It works!

IMPORTANT: Asciidoctor is awesome, don't forget!

CAUTION: Don't forget to add the `...-caption` document attributes in the header of the document on GitHub.

WARNING: You have no reason not to use Asciidoctor.

=== Images (UML-Diagrams)

==== plantuml-diagram only w/o puml-file

[source,asciidoc]
----
 image::http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKhEIImkLWX8BIhEprEevb9Gq4tBB2ekyKlCJRLI22ufoinBnovOo-MGcfS2D080[]
----

will be rendered to

image::http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKhEIImkLWX8BIhEprEevb9Gq4tBB2ekyKlCJRLI22ufoinBnovOo-MGcfS2D080[]

You can easily reverse-engineer this diagram at

https://www.plantuml.com/plantuml/uml/

Just paste the url and click kbd:[Decode URL]

==== plantuml-diagram reffering to puml-file

.referring to <project-root>/plantuml/cld.puml
[source,asciidoc]
----
 image::http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/htl-leonding/autograding-demo-jdk/main/plantuml/cld.puml[]
----

image::http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/htl-leonding/autograding-demo-jdk/main/plantuml/cld.puml[]

* When you update your puml-file, this image will be updated too

IMPORTANT: Maybe in private repos are permission issues

=== Collapsible

.see content
[%collapsible]
====
* Hello world
====

=== Source Code

[source,asciidoc]
----
 [source, java]
 ----
 include::https://raw.githubusercontent.com/htl-leonding/autograding-demo-jdk/main/hello-world/src/main/java/at/htl/helloworld/Main.java[]
 ----
----


[source,java,linenos]
----
include::https://raw.githubusercontent.com/htl-leonding/autograding-demo-jdk/main/hello-world/src/main/java/at/htl/helloworld/Main.java[]
----


=== Sources

* https://blog.doubleslash.de/github-readme-r-i-p-markdown-es-lebe-asciidoc/[Github-README: R.I.P. Markdown – es lebe AsciiDoc!]
* https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74[GitHub Flavored Asciidoc (GFA)]
* https://gist.github.com/powerman/d56b2675dfed38deb298[Asciidoc cheatsheet for GitHub]
* https://www.informatik.htw-dresden.de/~zirkelba/praktika/se/arbeiten-mit-git-und-asciidoc/[Arbeiten mit Git und AsciiDoc] <- geniale Seite!
* https://blog.anoff.io/2018-07-31-diagrams-with-plantuml/[Markdown native diagrams with PlantUML]
* https://blog.anoff.io/puml-cheatsheet.pdf[plantuml-cheatsheet]
* https://github.com/github/markup#markups[supported markups in github]


== Further stuff

Actually wanted demoing autograding, but got distracted ...